name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, fileinfo
        coverage: xdebug

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS testing;"
        php artisan migrate

    # - name: Execute tests (Unit and Feature tests)
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_DATABASE: testing
    #     DB_USERNAME: root
    #     DB_PASSWORD: password
    #   run: vendor/bin/phpunit --coverage-text

    # - name: Execute tests (Policies)
    #   env:
    #     DB_CONNECTION: mysql
    #     DB_DATABASE: testing
    #     DB_USERNAME: root
    #     DB_PASSWORD: password
    #   run: vendor/bin/phpunit --testsuite Feature --filter Policy

    - name: Execute Laravel Pint
      run: vendor/bin/pint --test 

    - name: Execute Larastan
      run: composer larastan -v 